In [1]:
import numpy as np

### Essentials

In [2]:
a=np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [3]:
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
a.dtype

dtype('int32')

In [5]:
b = np.array([1.,2.3,2.4])
b.dtype

dtype('float64')

In [6]:
c = np.array([1,2,3,4],dtype='float64')
c

array([1., 2., 3., 4.])

In [7]:
c.dtype

dtype('float64')

<hr />

### 2D Arrays

In [8]:
d = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [9]:
d.shape

(3, 4)

In [10]:
d.ndim

2

In [11]:
d.size

12

<hr />

### Slicing

In [12]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
d[1]

array([5, 6, 7, 8])

In [14]:
d[:,1]

array([ 2,  6, 10])

In [15]:
d[1,2]

7

In [16]:
d[1,0:2]

array([5, 6])

In [17]:
d[1,1:]

array([6, 7, 8])

In [18]:
e = d[:2,1:]

e, e.shape

(array([[2, 3, 4],
        [6, 7, 8]]),
 (2, 3))

In [19]:
e.ndim

2

In [20]:
e[1,1]

7

In [21]:
d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
d[1,1]=1000

In [23]:
d

array([[   1,    2,    3,    4],
       [   5, 1000,    7,    8],
       [   9,   10,   11,   12]])

In [24]:
d[1,1:]

array([1000,    7,    8])

In [25]:
d[1,1:]=-1
d

array([[ 1,  2,  3,  4],
       [ 5, -1, -1, -1],
       [ 9, 10, 11, 12]])

<hr />

### Array functions

In [26]:
d

array([[ 1,  2,  3,  4],
       [ 5, -1, -1, -1],
       [ 9, 10, 11, 12]])

In [27]:
d.flatten()

array([ 1,  2,  3,  4,  5, -1, -1, -1,  9, 10, 11, 12])

In [28]:
d.max()

12

In [29]:
d.min()

-1

In [30]:
d.max(axis=0)

array([ 9, 10, 11, 12])

In [31]:
d.min(axis=0)

array([ 1, -1, -1, -1])

In [32]:
d.max(axis=1)

array([ 4,  5, 12])

In [33]:
d.sum()

54

In [34]:
d.sum(axis=0)

array([15, 11, 13, 15])

<hr />

### Ranges & Random

In [35]:
np.arange(1,100,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [36]:
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [37]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

In [38]:
np.linspace(1 ,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [39]:
np.linspace(0 ,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [40]:
np.random.randint(5,20,(5,6))

array([[ 9, 11,  5,  7,  8, 13],
       [19, 17, 14, 17,  7, 17],
       [13,  9, 12,  7, 11, 18],
       [ 5, 17, 14, 14, 16, 18],
       [ 7, 11,  6, 10, 17, 10]])

In [41]:
np.random.random((3,4))

array([[0.14478676, 0.95805858, 0.91333666, 0.79134038],
       [0.53351518, 0.69962666, 0.61249179, 0.08494744],
       [0.85766969, 0.61972768, 0.49565112, 0.05577672]])

In [42]:
f = np.random.randint(5,20,(5,6))
f

array([[17, 16, 11, 12, 18, 13],
       [18, 17, 10, 10, 18, 17],
       [ 5, 13, 11, 14, 19, 12],
       [12,  5, 18, 13, 19,  7],
       [17, 12, 10, 10, 13, 19]])

In [43]:
f.shape

(5, 6)

In [44]:
f.reshape((6,5))

array([[17, 16, 11, 12, 18],
       [13, 18, 17, 10, 10],
       [18, 17,  5, 13, 11],
       [14, 19, 12, 12,  5],
       [18, 13, 19,  7, 17],
       [12, 10, 10, 13, 19]])

In [45]:
f.reshape((3,-1))

array([[17, 16, 11, 12, 18, 13, 18, 17, 10, 10],
       [18, 17,  5, 13, 11, 14, 19, 12, 12,  5],
       [18, 13, 19,  7, 17, 12, 10, 10, 13, 19]])

In [46]:
f.reshape((-1,10))

array([[17, 16, 11, 12, 18, 13, 18, 17, 10, 10],
       [18, 17,  5, 13, 11, 14, 19, 12, 12,  5],
       [18, 13, 19,  7, 17, 12, 10, 10, 13, 19]])

<hr />

### Matrix Operations

In [47]:
g = np.random.randint(5,20,(5,6))
f,g

(array([[17, 16, 11, 12, 18, 13],
        [18, 17, 10, 10, 18, 17],
        [ 5, 13, 11, 14, 19, 12],
        [12,  5, 18, 13, 19,  7],
        [17, 12, 10, 10, 13, 19]]),
 array([[ 8,  6, 17,  6,  5,  9],
        [15, 17, 15, 10, 16, 19],
        [ 9, 14,  7, 11,  7,  7],
        [18,  5, 10, 12,  8, 16],
        [10, 16,  5,  9, 12,  6]]))

In [48]:
f.shape, g.shape

((5, 6), (5, 6))

In [49]:
res = f+g
res

array([[25, 22, 28, 18, 23, 22],
       [33, 34, 25, 20, 34, 36],
       [14, 27, 18, 25, 26, 19],
       [30, 10, 28, 25, 27, 23],
       [27, 28, 15, 19, 25, 25]])

In [50]:
f*g

array([[136,  96, 187,  72,  90, 117],
       [270, 289, 150, 100, 288, 323],
       [ 45, 182,  77, 154, 133,  84],
       [216,  25, 180, 156, 152, 112],
       [170, 192,  50,  90, 156, 114]])

In [51]:
f/g

array([[2.125     , 2.66666667, 0.64705882, 2.        , 3.6       ,
        1.44444444],
       [1.2       , 1.        , 0.66666667, 1.        , 1.125     ,
        0.89473684],
       [0.55555556, 0.92857143, 1.57142857, 1.27272727, 2.71428571,
        1.71428571],
       [0.66666667, 1.        , 1.8       , 1.08333333, 2.375     ,
        0.4375    ],
       [1.7       , 0.75      , 2.        , 1.11111111, 1.08333333,
        3.16666667]])

In [52]:
f*5, f+1000

(array([[85, 80, 55, 60, 90, 65],
        [90, 85, 50, 50, 90, 85],
        [25, 65, 55, 70, 95, 60],
        [60, 25, 90, 65, 95, 35],
        [85, 60, 50, 50, 65, 95]]),
 array([[1017, 1016, 1011, 1012, 1018, 1013],
        [1018, 1017, 1010, 1010, 1018, 1017],
        [1005, 1013, 1011, 1014, 1019, 1012],
        [1012, 1005, 1018, 1013, 1019, 1007],
        [1017, 1012, 1010, 1010, 1013, 1019]]))

In [53]:
h = np.random.randint(5,20,(6,3))
h

array([[ 6, 12,  6],
       [14, 13,  6],
       [ 9, 19, 15],
       [13, 16, 14],
       [14, 10, 13],
       [11, 14, 16]])

In [54]:
f.shape, h.shape

((5, 6), (6, 3))

#### Matrix Multiplication

In [55]:
f@h

array([[ 976, 1175,  973],
       [1005, 1205, 1006],
       [ 891, 1020,  908],
       [ 816, 1047,  913],
       [ 881, 1106,  937]])

In [56]:
f.dot(h)

array([[ 976, 1175,  973],
       [1005, 1205, 1006],
       [ 891, 1020,  908],
       [ 816, 1047,  913],
       [ 881, 1106,  937]])

#### Matrix Transpose

In [57]:
f,f.T

(array([[17, 16, 11, 12, 18, 13],
        [18, 17, 10, 10, 18, 17],
        [ 5, 13, 11, 14, 19, 12],
        [12,  5, 18, 13, 19,  7],
        [17, 12, 10, 10, 13, 19]]),
 array([[17, 18,  5, 12, 17],
        [16, 17, 13,  5, 12],
        [11, 10, 11, 18, 10],
        [12, 10, 14, 13, 10],
        [18, 18, 19, 19, 13],
        [13, 17, 12,  7, 19]]))

In [58]:
f.transpose()

array([[17, 18,  5, 12, 17],
       [16, 17, 13,  5, 12],
       [11, 10, 11, 18, 10],
       [12, 10, 14, 13, 10],
       [18, 18, 19, 19, 13],
       [13, 17, 12,  7, 19]])

<hr />

In [59]:
np.eye(5,dtype='int32')

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Changing an array's data type:

In [60]:
f.astype('float')

array([[17., 16., 11., 12., 18., 13.],
       [18., 17., 10., 10., 18., 17.],
       [ 5., 13., 11., 14., 19., 12.],
       [12.,  5., 18., 13., 19.,  7.],
       [17., 12., 10., 10., 13., 19.]])

In [61]:
k = np.random.randint(5,20,(4,4))
k

array([[ 9, 11, 10, 14],
       [ 5,  5,  5,  7],
       [11, 10,  9, 14],
       [19,  8, 13,  9]])

#### Inverse of a Matrix

In [62]:
np.linalg.inv(k)

array([[-0.07586207, -0.54482759,  0.31724138,  0.04827586],
       [ 0.92413793, -2.54482759,  0.31724138,  0.04827586],
       [-0.07586207,  1.45517241, -0.68275862,  0.04827586],
       [-0.55172414,  1.31034483,  0.03448276, -0.10344828]])

In [63]:
f

array([[17, 16, 11, 12, 18, 13],
       [18, 17, 10, 10, 18, 17],
       [ 5, 13, 11, 14, 19, 12],
       [12,  5, 18, 13, 19,  7],
       [17, 12, 10, 10, 13, 19]])

In [64]:
f[f>12]=-1

In [65]:
f

array([[-1, -1, 11, 12, -1, -1],
       [-1, -1, 10, 10, -1, -1],
       [ 5, -1, 11, -1, -1, 12],
       [12,  5, -1, -1, -1,  7],
       [-1, 12, 10, 10, -1, -1]])

#### Main Diagonal

In [66]:
f.diagonal()

array([-1, -1, 11, -1, -1])

#### Secondary Diagonal

In [67]:
diag = np.fliplr(f).diagonal()
diag

array([-1, -1, -1, -1, 12])

In [68]:
diag[diag==5].size

0

In [69]:
for row in d:
    for element in row:
        if(element==4):
            print("found")

found
