In [55]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import plotly.express as px
from sklearn import preprocessing
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder


In [56]:
medical_df = pd.read_csv("C:/dev/sklearn_freeCodeAcademy/full_course_Aakash_N_S/insurance.csv", encoding="utf-8-sig", low_memory=False)

In [57]:
non_smoker_df = medical_df[medical_df.smoker == "no"]

smoker_codes = {"no":0, "yes":1}
medical_df["smoker_codes"] = medical_df.smoker.map(smoker_codes)

sex_codes = {"female": 0, "male": 1}
medical_df["sex_codes"] = medical_df.sex.map(sex_codes)

enc = preprocessing.OneHotEncoder()
enc.fit(medical_df[["region"]])

enc.transform([["northeast"],
                ["northwest"]]).toarray()

one_hot = enc.transform(medical_df[["region"]]).toarray()

medical_df[["northeast", "northwest", "southeast", "southwest"]] = one_hot

def rmse(targets, predictions):
    return np.sqrt(np.mean(np.square(targets - predictions)))


c:\dev\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [58]:
numeric_cols = ["age", "bmi", "children"]
scaler = StandardScaler()
scaler.fit(medical_df[numeric_cols])

,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True


In [59]:
scaler.mean_

array([39.20702541, 30.66339686,  1.09491779])

In [60]:
scaler.var_

array([197.25385199,  37.16008997,   1.45212664])

In [61]:
scaled_inputs = scaler.transform(medical_df[numeric_cols])
scaled_inputs

array([[-1.43876426, -0.45332   , -0.90861367],
       [-1.50996545,  0.5096211 , -0.07876719],
       [-0.79795355,  0.38330685,  1.58092576],
       ...,
       [-1.50996545,  1.0148781 , -0.90861367],
       [-1.29636188, -0.79781341, -0.90861367],
       [ 1.55168573, -0.26138796, -0.90861367]], shape=(1338, 3))

In [62]:
cat_cols = ["smoker_codes", "sex_codes", "northeast", "northwest", "southeast", "southwest"]
categorical_data = medical_df[cat_cols].values

In [63]:
inputs = np.concatenate((scaled_inputs, categorical_data), axis=1)
targets = medical_df.charges

model = LinearRegression().fit(inputs, targets)

predictions = model.predict(inputs)

loss = rmse(targets, predictions)

print("loss:", loss)

loss: 6041.679651174452


In [64]:
inputs[0]

array([-1.43876426, -0.45332   , -0.90861367,  1.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  1.        ])

In [ ]:
weights_df  = pd.DataFrame({
    "feature": np.append(numeric_cols + cat_cols, 1),
    "weight": np.append(model.coef_, model.intercept_)
})
weights_df.sort_values("weight",  ascending=False)

,feature,weight
3,smoker_codes,23848.534542
9,1,8466.483215
0,age,3607.472736
1,bmi,2067.691966
5,northeast,587.009235
2,children,572.998210
6,northwest,234.045336
4,sex_codes,-131.314359
8,southwest,-373.041756
7,southeast,-448.012814


In [66]:
model.coef_

array([ 3607.47273619,  2067.69196584,   572.99820995, 23848.53454191,
        -131.3143594 ,   587.00923503,   234.0453356 ,  -448.01281436,
        -373.04175627])

In [67]:
new_cutomers = [[28,30,2,1,0,0,1,0,0.]]

In [68]:
scaler.transform([[28,30,2]])

c:\dev\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.79795355, -0.10882659,  0.75107928]])

In [69]:
model.predict([[-0.79795355, -0.10882659,  0.75107928, 1,0,0,1,0,0.]])

array([29875.81463371])